### PR TITLE
Change APIs

### PR DESCRIPTION
**Pull request by jessehanley**

### CODE REVIEW

**Comment by jessehanley** [comment]
New orders aren't firing for Woo, believe that's because of the new checkout.

**Comment by jessehanley** [comment]
https://github.com/bentonow/bento-wordpress-sdk/pull/22/commits/6ce472e58248adc9a9f23a8d68f401ae3023bbd5 this change seems to now double fire which makes sense. Maybe should just do a conditional check if Woo version 8...?

**Comment by jessehanley** [comment]
Looks like `woocommerce_new_order` is the one.

**Comment by jessehanley** [comment]
Okay, also added: WPForms 

Refactored: Elementor, Bricks, etc load paths.

@joedawson / @ziptied is how I'm loading this stuff correct in the PHP/WordPress sense of things? My assumption is that I have to do the class_exists checks whenever I'm extending a plugin, but not if I'm tying into a hook (given they won't ever fire if the plugin doesn't exist. 

```php
require_once 'inc/class-bento-events-controller.php';
require_once 'inc/forms/class-bento-bricks-form-handler.php';
require_once 'inc/forms/class-bento-elementor-form-handler.php';

Bento_Events_Controller::init();
Bento_Bricks_Form_Handler::init(); # 
Bento_Elementor_Form_Handler::init();

if ( class_exists( 'WPForms' ) ) {
	require_once 'inc/forms/class-wp-forms-form-handler.php';
}
}
```

Any other obvious mistakes let me know!

**Comment by jessehanley** [comment]
Thrive now supported! Woo!

**Comment by joedawson** [comment]
> @joedawson / @ziptied is how I'm loading this stuff correct in the PHP/WordPress sense of things? My assumption is that I have to do the class_exists checks whenever I'm extending a plugin, but not if I'm tying into a hook (given they won't ever fire if the plugin doesn't exist.

Looks good to me @jessehanley, in terms of checking plugins a plugins existence via `class_exists`.

The only issue I can currently see is inconsistencies with translatable strings. The current plugin uses `bentonow` as the text domain.

It would be wise to stick with a single domain throughout the plugin, avoiding things such as: `elementor-forms-bento-action` ([example](https://github.com/bentonow/bento-wordpress-sdk/blob/feat/upgrade-v2/form-actions/bento.php#L39)) and `wpforms-lite` ([example](https://github.com/bentonow/bento-wordpress-sdk/blob/feat/upgrade-v2/inc/forms/class-wp-forms-form-handler.php#L367)) and replacing all instances with `bentonow`.

Although the current plugin doesn't provide translations, it sets a good foundation for the future and also should any existing sites want to add their own translations they can easily be identified by a single domain.

**Comment by jessehanley** [comment]
@jessehanley awesome feedback! Very much appreciate you taking a look. Would you like to give us a hand doing any clean up/refactoring or good to ship this as the next version (I'll do that next week Monday)?

**Pull request merged**
