### PR TITLE
LearnDash Integration

### LINKED ISSUE #8: LearnDash Integration
Placeholder ticket for LearnDash integration for Bento. 

- [ ] Setup initial integration
- [ ] Send Events
- [ ] Course Complete
- [ ] Course Incomplete
- [ ] Lesson Complete
- [ ] Lesson Incomplete
- [ ] Topic Complete
- [ ] Topic Incomplete
- [ ] Quiz Complete
- [ ] Quiz Incomplete
- [ ] New Drip Content available (per post type)
- [ ] User not logged in X days
- [ ] User not completed a lesson in X days
- [ ] User earns a new certificate
- [ ] Users assignment has been graded
- [ ] Users essay has been graded 
- [ ] Users assignment has a new comment
- [ ] User enrolls in a course
- [ ] User enrolls in a group
- [ ] Users buys a course
- [ ] User buys a group
- [ ] TBC

### PR DESCRIPTION
**Pull request by estevao90**
Implements the LearnDash Integration.
close #8

### CODE REVIEW

**Comment by jessehanley** [comment]
Hey @codemonkey-jack and @estevao90! 

Thank you so much for this PR — just to confirm: 
- Existing WordPress/WooCommerce functionality will continue to run as it always has.
- The LearnDash side of things _will not_ impact performance for stores just running WooCommerce (not LearnDash).
- No cron runs if LearnDash is not enabled.

And questions: 
- Are there performance considerations we should caveat with the plugin or add to the readme? 

Additionally: 
- Can the LearnDash cron settings _only_ be visible if LearnDash is installed? Maybe also rename that cron header to  `Configure Bento's LearnDash Background Events Sender` just so it's not confusing.

**Comment by codemonkey-jack** [comment]
@jessehanley 

> Existing WordPress/WooCommerce functionality will continue to run as it always has.

Correct.

> The LearnDash side of things will not impact performance for stores just running WooCommerce (not LearnDash).

Correct.

> No cron runs if LearnDash is not enabled.

Correct.

>  Are there performance considerations we should caveat with the plugin or add to the readme?

I would recommend adding a note that if the user is using shared hosting the recommendation is to delay the cron event by setting it to say 10 minutes to reduce load on resource usage, especially important for those with hosts that measure I/O as a metric for resource usage. Some hosts even limit cron events to every 15 minutes as the quickest option.

> Can the LearnDash cron settings only be visible if LearnDash is installed? Maybe also rename that cron header to Configure Bento's LearnDash Background Events Sender just so it's not confusing.

@estevao90 Can you do the above, please?

**Comment by estevao90** [comment]
Sure!

Changes added. Some events are not related to LearnDash by design (ex: user_not_logged_since). We created a generic class for them. In the future, you can remove the LearnDash verification and add more events to the WP_Bento_Events or even create other integration classes.

**Comment by jessehanley** [comment]
Merging in, thanks @estevao90!

**Pull request merged**
